ktor:
  application:
    modules:
      - com.encore.music.ApplicationKt.module
  deployment:
    port: 8080

spotify:
  client:
    id: $ENCORE_SPOTIFY_CLIENT_ID
    secret: $ENCORE_SPOTIFY_CLIENT_SECRET
